/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_baidu_iov_vision_ability_core_bean_FaceInfo */

#ifndef _Included_com_baidu_iov_vision_ability_core_bean_FaceInfo
#define _Included_com_baidu_iov_vision_ability_core_bean_FaceInfo

#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_baidu_iov_vision_ability_core_bean_FaceInfo
 * Method:    init
 * Signature: (Ljava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_baidu_iov_vision_ability_core_bean_FaceInfo_init
        (JNIEnv *env, jobject thiz, jobject buffer);

/*
 * Class:     com_baidu_iov_vision_ability_core_bean_FaceInfo
 * Method:    getBufferSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_baidu_iov_vision_ability_core_bean_FaceInfo_getBufferSize
        (JNIEnv *env, jobject thiz);


/*
 * Class:     com_baidu_iov_vision_ability_core_bean_FaceInfo
 * Method:    id
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_baidu_iov_vision_ability_core_bean_FaceInfo_id__
        (JNIEnv *env, jobject thiz);

/*
 * Class:     com_baidu_iov_vision_ability_core_bean_FaceInfo
 * Method:    rectConfidence
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_baidu_iov_vision_ability_core_bean_FaceInfo_rectConfidence__
        (JNIEnv *env, jobject thiz);

/*
 * Class:     com_baidu_iov_vision_ability_core_bean_FaceInfo
 * Method:    singleCallState
 * Signature: ()I
 */
JNIEXPORT jboolean JNICALL Java_com_baidu_iov_vision_ability_core_bean_FaceInfo_singleCallState
        (JNIEnv *env, jobject thiz);

/*
 * Class:     com_baidu_iov_vision_ability_core_bean_FaceInfo
 * Method:    rect
 * Signature: ()[F
 */
JNIEXPORT jint JNICALL Java_com_baidu_iov_vision_ability_core_bean_FaceInfo_singleDangerDriveState
        (JNIEnv *env, jobject thiz);

/*
 * Class:     com_baidu_iov_vision_ability_core_bean_FaceInfo
 * Method:    rect
 * Signature: ()[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_baidu_iov_vision_ability_core_bean_FaceInfo_rect
        (JNIEnv *env, jobject thiz);
/*
 * Class:     com_baidu_iov_vision_ability_core_bean_FaceInfo
 * Method:    landmarkConfidence
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_baidu_iov_vision_ability_core_bean_FaceInfo_landmarkConfidence
        (JNIEnv *env, jobject thiz);

/*
 * Class:     com_baidu_iov_vision_ability_core_bean_FaceInfo
 * Method:    landmark2D106
 * Signature: ()[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_baidu_iov_vision_ability_core_bean_FaceInfo_landmark2D106
        (JNIEnv *env, jobject thiz);

/*
 * Class:     com_baidu_iov_vision_ability_core_bean_FaceInfo
 * Method:    landmark2D68
 * Signature: ()[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_baidu_iov_vision_ability_core_bean_FaceInfo_landmark2D68
        (JNIEnv *env, jobject thiz);

/*
 * Class:     com_baidu_iov_vision_ability_core_bean_FaceInfo
 * Method:    landmark3D68
 * Signature: ()[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_baidu_iov_vision_ability_core_bean_FaceInfo_landmark3D68
        (JNIEnv *env, jobject thiz);

/*
 * Class:     com_baidu_iov_vision_ability_core_bean_FaceInfo
 * Method:    feature
 * Signature: ()[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_baidu_iov_vision_ability_core_bean_FaceInfo_feature
        (JNIEnv *env, jobject thiz);

/*
 * Class:     com_baidu_iov_vision_ability_core_bean_FaceInfo
 * Method:    noInteractLivingState
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_baidu_iov_vision_ability_core_bean_FaceInfo_noInteractLivingState
        (JNIEnv *env, jobject thiz);

/*
 * Class:     com_baidu_iov_vision_ability_core_bean_FaceInfo
 * Method:    noInteractLivingSingleState
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_baidu_iov_vision_ability_core_bean_FaceInfo_noInteractLivingSingleState
        (JNIEnv *env, jobject thiz);

/*
 * Class:     com_baidu_iov_vision_ability_core_bean_FaceInfo
 * Method:    interactLivingState
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_baidu_iov_vision_ability_core_bean_FaceInfo_interactLivingState
        (JNIEnv *env, jobject thiz);

/*
 * Class:     com_baidu_iov_vision_ability_core_bean_FaceInfo
 * Method:    dangerousState
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_baidu_iov_vision_ability_core_bean_FaceInfo_dangerousState
        (JNIEnv *env, jobject thiz);

/*
 * Class:     com_baidu_iov_vision_ability_core_bean_FaceInfo
 * Method:    dangerousSmokeState
 * Signature: ()[F
 */
JNIEXPORT jintArray JNICALL Java_com_baidu_iov_vision_ability_core_bean_FaceInfo_dangerousSmokeState
        (JNIEnv *env, jobject thiz);

/*
 * Class:     com_baidu_iov_vision_ability_core_bean_FaceInfo
 * Method:    dangerousDrinkState
 * Signature: ()[F
 */
JNIEXPORT jintArray JNICALL Java_com_baidu_iov_vision_ability_core_bean_FaceInfo_dangerousDrinkState
        (JNIEnv *env, jobject thiz);

/*
 * Class:     com_baidu_iov_vision_ability_core_bean_FaceInfo
 * Method:    dangerousMouthState
 * Signature: ()[F
 */
JNIEXPORT jintArray JNICALL Java_com_baidu_iov_vision_ability_core_bean_FaceInfo_dangerousMouthState
        (JNIEnv *env, jobject thiz);

/*
 * Class:     com_baidu_iov_vision_ability_core_bean_FaceInfo
 * Method:    dangerousCallState
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_baidu_iov_vision_ability_core_bean_FaceInfo_dangerousCallState
        (JNIEnv *env, jobject thiz);

/*
 * Class:     com_baidu_iov_vision_ability_core_bean_FaceInfo
 * Method:    dangerousPhoneCallState
 * Signature: ()[F
 */
JNIEXPORT jintArray JNICALL Java_com_baidu_iov_vision_ability_core_bean_FaceInfo_dangerousPhoneCallState
        (JNIEnv *env, jobject thiz);

/*
 * Class:     com_baidu_iov_vision_ability_core_bean_FaceInfo
 * Method:    fatigueState
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_baidu_iov_vision_ability_core_bean_FaceInfo_fatigueState
        (JNIEnv *env, jobject thiz);

/*
 * Class:     com_baidu_iov_vision_ability_core_bean_FaceInfo
 * Method:    fatigueEyeCloseState
 * Signature: ()[F
 */
JNIEXPORT jintArray JNICALL Java_com_baidu_iov_vision_ability_core_bean_FaceInfo_fatigueEyeCloseState
        (JNIEnv *env, jobject thiz);

/*
 * Class:     com_baidu_iov_vision_ability_core_bean_FaceInfo
 * Method:    fatigueYawnState
 * Signature: ()[F
 */
JNIEXPORT jintArray JNICALL Java_com_baidu_iov_vision_ability_core_bean_FaceInfo_fatigueYawnState
        (JNIEnv *env, jobject thiz);

/*
 * Class:     com_baidu_iov_vision_ability_core_bean_FaceInfo
 * Method:    attentionState
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_baidu_iov_vision_ability_core_bean_FaceInfo_attentionState
        (JNIEnv *env, jobject thiz);

/*
 * Class:     com_baidu_iov_vision_ability_core_bean_FaceInfo
 * Method:    attentionLookLeftState
 * Signature: ()[F
 */
JNIEXPORT jintArray JNICALL Java_com_baidu_iov_vision_ability_core_bean_FaceInfo_attentionLookLeftState
        (JNIEnv *env, jobject thiz);

/*
 * Class:     com_baidu_iov_vision_ability_core_bean_FaceInfo
 * Method:    attentionLookRightState
 * Signature: ()[F
 */
JNIEXPORT jintArray JNICALL Java_com_baidu_iov_vision_ability_core_bean_FaceInfo_attentionLookRightState
        (JNIEnv *env, jobject thiz);

/*
 * Class:     com_baidu_iov_vision_ability_core_bean_FaceInfo
 * Method:    attentionLookUpState
 * Signature: ()[F
 */
JNIEXPORT jintArray JNICALL Java_com_baidu_iov_vision_ability_core_bean_FaceInfo_attentionLookUpState
        (JNIEnv *env, jobject thiz);

/*
 * Class:     com_baidu_iov_vision_ability_core_bean_FaceInfo
 * Method:    attentionLookDownState
 * Signature: ()[F
 */
JNIEXPORT jintArray JNICALL Java_com_baidu_iov_vision_ability_core_bean_FaceInfo_attentionLookDownState
        (JNIEnv *env, jobject thiz);

/*
 * Class:     com_baidu_iov_vision_ability_core_bean_FaceInfo
 * Method:    smallEyeState
 * Signature: ()[F
 */
JNIEXPORT jintArray JNICALL Java_com_baidu_iov_vision_ability_core_bean_FaceInfo_smallEyeState
        (JNIEnv *env, jobject thiz);

/*
 * Class:     com_baidu_iov_vision_ability_core_bean_FaceInfo
 * Method:    attributeEmotionState
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_baidu_iov_vision_ability_core_bean_FaceInfo_attributeEmotionState
        (JNIEnv *env, jobject thiz);

/*
 * Class:     com_baidu_iov_vision_ability_core_bean_FaceInfo
 * Method:    attributeGlassState
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_baidu_iov_vision_ability_core_bean_FaceInfo_attributeGlassState
        (JNIEnv *env, jobject thiz);

/*
 * Class:     com_baidu_iov_vision_ability_core_bean_FaceInfo
 * Method:    attributeGenderState
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_baidu_iov_vision_ability_core_bean_FaceInfo_attributeGenderState
        (JNIEnv *env, jobject thiz);

/*
 * Class:     com_baidu_iov_vision_ability_core_bean_FaceInfo
 * Method:    attributeRaceState
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_baidu_iov_vision_ability_core_bean_FaceInfo_attributeRaceState
        (JNIEnv *env, jobject thiz);

/*
 * Class:     com_baidu_iov_vision_ability_core_bean_FaceInfo
 * Method:    attributeAgeState
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_baidu_iov_vision_ability_core_bean_FaceInfo_attributeAgeState
        (JNIEnv *env, jobject thiz);

/*
 * Class:     com_baidu_iov_vision_ability_core_bean_FaceInfo
 * Method:    eyeCloseConfidence
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_baidu_iov_vision_ability_core_bean_FaceInfo_eyeCloseConfidence
        (JNIEnv *env, jobject thiz);

/*
 * Class:     com_baidu_iov_vision_ability_core_bean_FaceInfo
 * Method:    eyeCentroid
 * Signature: ()[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_baidu_iov_vision_ability_core_bean_FaceInfo_eyeCentroid
        (JNIEnv *env, jobject thiz);

/*
 * Class:     com_baidu_iov_vision_ability_core_bean_FaceInfo
 * Method:    eyeTracking
 * Signature: ()[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_baidu_iov_vision_ability_core_bean_FaceInfo_eyeTracking
        (JNIEnv *env, jobject thiz);

/*
 * Class:     com_baidu_iov_vision_ability_core_bean_FaceInfo
 * Method:    eyeWakingState
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_baidu_iov_vision_ability_core_bean_FaceInfo_eyeWakingState
        (JNIEnv *env, jobject thiz);

/*
 * Class:     com_baidu_iov_vision_ability_core_bean_FaceInfo
 * Method:    headBehaviorState
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_baidu_iov_vision_ability_core_bean_FaceInfo_headBehaviorState
        (JNIEnv *env, jobject thiz);

/*
 * Class:     com_baidu_iov_vision_ability_core_bean_FaceInfo
 * Method:    headDeflection
 * Signature: ()[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_baidu_iov_vision_ability_core_bean_FaceInfo_headDeflection
        (JNIEnv *env, jobject thiz);

/*
 * Class:     com_baidu_iov_vision_ability_core_bean_FaceInfo
 * Method:    headPosition
 * Signature: ()[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_baidu_iov_vision_ability_core_bean_FaceInfo_headPosition
        (JNIEnv *env, jobject thiz);

/*
 * Class:     com_baidu_iov_vision_ability_core_bean_FaceInfo
 * Method:    beQuiteState
 * Signature: ()[F
 */
JNIEXPORT jintArray JNICALL Java_com_baidu_iov_vision_ability_core_bean_FaceInfo_beQuiteState
        (JNIEnv *env, jobject thiz);

/*
 * Class:     com_baidu_iov_vision_ability_core_bean_FaceInfo
 * Method:    isBlur
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_baidu_iov_vision_ability_core_bean_FaceInfo_isBlur
        (JNIEnv *env, jobject thiz);

/*
 * Class:     com_baidu_iov_vision_ability_core_bean_FaceInfo
 * Method:    isBlocked
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_baidu_iov_vision_ability_core_bean_FaceInfo_isFaceBlocked
        (JNIEnv *env, jobject thiz);

/*
 * Class:     com_baidu_iov_vision_ability_core_bean_FaceInfo
 * Method:    isSingleBlocked
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_baidu_iov_vision_ability_core_bean_FaceInfo_isSingleBlocked
        (JNIEnv *env, jobject thiz);

/*
 * Class:     com_baidu_iov_vision_ability_core_bean_FaceInfo
 * Method:    isNoisy
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_baidu_iov_vision_ability_core_bean_FaceInfo_isNoisy
        (JNIEnv *env, jobject thiz);

/*
 * Class:     com_baidu_iov_vision_ability_core_bean_FaceInfo
 * Method:    isCameraBlocked
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_baidu_iov_vision_ability_core_bean_FaceInfo_isCameraBlocked
        (JNIEnv *env, jobject thiz);

/*
 * Class:     com_baidu_iov_vision_ability_core_bean_FaceInfo
 * Method:    noMoving
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_baidu_iov_vision_ability_core_bean_FaceInfo_noMoving
        (JNIEnv *env, jobject thiz);

/*
 * Class:     com_baidu_iov_vision_ability_core_bean_FaceInfo
 * Method:    trackState
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_baidu_iov_vision_ability_core_bean_FaceInfo_trackState
        (JNIEnv *env, jobject thiz);

/*
 * Class:     com_baidu_iov_vision_ability_core_bean_FaceInfo
 * Method:    searchState
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_baidu_iov_vision_ability_core_bean_FaceInfo_searchState
        (JNIEnv *env, jobject thiz);

/*
 * Class:     com_baidu_iov_vision_ability_core_bean_FaceInfo
 * Method:    leftEyeGazeOrigin
 * Signature: ()[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_baidu_iov_vision_ability_core_bean_FaceInfo_leftEyeGazeOrigin
        (JNIEnv *env, jobject thiz);

/*
 * Class:     com_baidu_iov_vision_ability_core_bean_FaceInfo
 * Method:    leftEyeGazeDirection
 * Signature: ()[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_baidu_iov_vision_ability_core_bean_FaceInfo_leftEyeGazeDirection
        (JNIEnv *env, jobject thiz);

/*
 * Class:     com_baidu_iov_vision_ability_core_bean_FaceInfo
 * Method:    rightEyeGazeOrigin
 * Signature: ()[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_baidu_iov_vision_ability_core_bean_FaceInfo_rightEyeGazeOrigin
        (JNIEnv *env, jobject thiz);

/*
 * Class:     com_baidu_iov_vision_ability_core_bean_FaceInfo
 * Method:    rightEyeGazeDirection
 * Signature: ()[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_baidu_iov_vision_ability_core_bean_FaceInfo_rightEyeGazeDirection
        (JNIEnv *env, jobject thiz);

/*
 * Class:     com_baidu_iov_vision_ability_core_bean_FaceInfo
 * Method:    leftEyelidOpening
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_baidu_iov_vision_ability_core_bean_FaceInfo_leftEyelidOpening
        (JNIEnv *env, jobject thiz);

/*
 * Class:     com_baidu_iov_vision_ability_core_bean_FaceInfo
 * Method:    rightEyelidOpening
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_baidu_iov_vision_ability_core_bean_FaceInfo_rightEyelidOpening
        (JNIEnv *env, jobject thiz);

/*
 * Class:     com_baidu_iov_vision_ability_core_bean_FaceInfo
 * Method:    leftEyelidState
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_baidu_iov_vision_ability_core_bean_FaceInfo_leftEyelidState
        (JNIEnv *env, jobject thiz);

/*
 * Class:     com_baidu_iov_vision_ability_core_bean_FaceInfo
 * Method:    rightEyelidState
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_baidu_iov_vision_ability_core_bean_FaceInfo_rightEyelidState
        (JNIEnv *env, jobject thiz);

/*
 * Class:     com_baidu_iov_vision_ability_core_bean_FaceInfo
 * Method:    eyeState
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_baidu_iov_vision_ability_core_bean_FaceInfo_eyeState
        (JNIEnv *env, jobject thiz);

/*
 * Class:     com_baidu_iov_vision_ability_core_bean_FaceInfo
 * Method:    leftEyeState
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_baidu_iov_vision_ability_core_bean_FaceInfo_leftEyeState
        (JNIEnv *env, jobject thiz);

/*
 * Class:     com_baidu_iov_vision_ability_core_bean_FaceInfo
 * Method:    rightEyeState
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_baidu_iov_vision_ability_core_bean_FaceInfo_rightEyeState
        (JNIEnv *env, jobject thiz);

/*
 * Class:     com_baidu_iov_vision_ability_core_bean_FaceInfo
 * Method:    eyeBlinkCloseSpeed
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_baidu_iov_vision_ability_core_bean_FaceInfo_eyeBlinkCloseSpeed
        (JNIEnv *env, jobject thiz);

/*
 * Class:     com_baidu_iov_vision_ability_core_bean_FaceInfo
 * Method:    eyeBlinkCloseStartTime
 * Signature: ()F
 */
JNIEXPORT jlong JNICALL Java_com_baidu_iov_vision_ability_core_bean_FaceInfo_eyeBlinkCloseStartTime
        (JNIEnv *env, jobject thiz);

/*
 * Class:     com_baidu_iov_vision_ability_core_bean_FaceInfo
 * Method:    eyeBlinkCloseStopTime
 * Signature: ()F
 */
JNIEXPORT jlong JNICALL Java_com_baidu_iov_vision_ability_core_bean_FaceInfo_eyeBlinkCloseStopTime
        (JNIEnv *env, jobject thiz);


/*
 * Class:     com_baidu_iov_vision_ability_core_bean_FaceInfo
 * Method:    eyeBlinkState
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_baidu_iov_vision_ability_core_bean_FaceInfo_eyeBlinkState
        (JNIEnv *env, jobject thiz);

/*
 * Class:     com_baidu_iov_vision_ability_core_bean_FaceInfo
 * Method:    eyeBlinkDuration
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_baidu_iov_vision_ability_core_bean_FaceInfo_eyeBlinkDuration
        (JNIEnv *env, jobject thiz);

/*
 * Class:     com_baidu_iov_vision_ability_core_bean_FaceInfo
 * Method:    noFaceState
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_com_baidu_iov_vision_ability_core_bean_FaceInfo_noFaceState
        (JNIEnv *env, jobject thiz);


#ifdef __cplusplus
}
#endif
#endif