/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_baidu_iov_vision_ability_core_bean_GestureInfo */

#ifndef _Included_com_baidu_iov_vision_ability_core_bean_GestureInfo
#define _Included_com_baidu_iov_vision_ability_core_bean_GestureInfo

#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_baidu_iov_vision_ability_core_bean_GestureInfo
 * Method:    init
 * Signature: (Ljava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_baidu_iov_vision_ability_core_bean_GestureInfo_init
        (JNIEnv *env, jobject thiz, jobject buffer);

/*
 * Class:     com_baidu_iov_vision_ability_core_bean_GestureInfo
 * Method:    getBufferSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_baidu_iov_vision_ability_core_bean_GestureInfo_getBufferSize
        (JNIEnv *env, jobject thiz);

/*
 * Class:     com_baidu_iov_vision_ability_core_bean_GestureInfo
 * Method:    id
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_baidu_iov_vision_ability_core_bean_GestureInfo_id__
        (JNIEnv *env, jobject thiz);

/*
 * Class:     com_baidu_iov_vision_ability_core_bean_GestureInfo
 * Method:    rectConfidence
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_baidu_iov_vision_ability_core_bean_GestureInfo_rectConfidence__
        (JNIEnv *env, jobject thiz);

/*
 * Class:     com_baidu_iov_vision_ability_core_bean_GestureInfo
 * Method:    rect
 * Signature: ()[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_baidu_iov_vision_ability_core_bean_GestureInfo_rect
        (JNIEnv *env, jobject thiz);

/*
 * Class:     com_baidu_iov_vision_ability_core_bean_GestureInfo
 * Method:    landmarkConfidence
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_baidu_iov_vision_ability_core_bean_GestureInfo_landmarkConfidence
        (JNIEnv *env, jobject thiz);

/*
 * Class:     com_baidu_iov_vision_ability_core_bean_GestureInfo
 * Method:    landmark
 * Signature: ()[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_baidu_iov_vision_ability_core_bean_GestureInfo_landmark
        (JNIEnv *env, jobject thiz);

/*
 * Class:     com_baidu_iov_vision_ability_core_bean_GestureInfo
 * Method:    type
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_baidu_iov_vision_ability_core_bean_GestureInfo_type
        (JNIEnv *env, jobject thiz);

/*
 * Class:     com_baidu_iov_vision_ability_core_bean_GestureInfo
 * Method:    singleType
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_baidu_iov_vision_ability_core_bean_GestureInfo_singleType
        (JNIEnv *env, jobject thiz);

/*
 * Class:     com_baidu_iov_vision_ability_core_bean_GestureInfo
 * Method:    staticType
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_baidu_iov_vision_ability_core_bean_GestureInfo_staticType
        (JNIEnv *env, jobject thiz);

/*
 * Class:     com_baidu_iov_vision_ability_core_bean_GestureInfo
 * Method:    dynamicType
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_baidu_iov_vision_ability_core_bean_GestureInfo_dynamicType
        (JNIEnv *env, jobject thiz);

#ifdef __cplusplus
}
#endif
#endif
