/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_baidu_iov_vision_ability_core_bean_FrameInfo */

#ifndef _Included_com_baidu_iov_vision_ability_core_bean_FrameInfo
#define _Included_com_baidu_iov_vision_ability_core_bean_FrameInfo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_baidu_iov_vision_ability_core_bean_FrameInfo
 * Method:    init
 * Signature: (Ljava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_baidu_iov_vision_ability_core_bean_FrameInfo_init
        (JNIEnv *env, jobject thiz, jobject buffer);

/*
 * Class:     com_baidu_iov_vision_ability_core_bean_FrameInfo
 * Method:    getBufferSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_baidu_iov_vision_ability_core_bean_FrameInfo_getBufferSize
        (JNIEnv *env, jobject thiz);

/*
 * Class:     com_baidu_iov_vision_ability_core_bean_FrameInfo
 * Method:    brightness
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_baidu_iov_vision_ability_core_bean_FrameInfo_brightness
        (JNIEnv *env, jobject thiz);

/*
 * Class:     com_baidu_iov_vision_ability_core_bean_FrameInfo
 * Method:    imageState
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_baidu_iov_vision_ability_core_bean_FrameInfo_imageState
        (JNIEnv *env, jobject thiz);

/*
 * Class:     com_baidu_iov_vision_ability_core_bean_FrameInfo
 * Method:    blockage
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_baidu_iov_vision_ability_core_bean_FrameInfo_blockage
        (JNIEnv *env, jobject thiz);

/*
 * Class:     com_baidu_iov_vision_ability_core_bean_FrameInfo
 * Method:    spoofed
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_baidu_iov_vision_ability_core_bean_FrameInfo_spoofed
        (JNIEnv *env, jobject thiz);

/*
 * Class:     com_baidu_iov_vision_ability_core_bean_FrameInfo
 * Method:    spoofed
 * Signature: ()I
 */
JNIEXPORT jlong JNICALL Java_com_baidu_iov_vision_ability_core_bean_FrameInfo_timestamp
        (JNIEnv *env, jobject thiz);

#ifdef __cplusplus
}
#endif
#endif
