// Auto generated by the plain buffer compiler.
// PLEASE DO NOT EDIT!
// source: model_config.proto

#ifndef PLAIN_BUFFER_GENERATED_MODEL_CONFIG_H
#define PLAIN_BUFFER_GENERATED_MODEL_CONFIG_H

#include <string>
#include <unordered_map>
#include <vector>

#include "plainbuffer/message_base.h"
#include "plainbuffer/schema.h"

namespace aura::vision {

class Model : public plainbuffer::MessageBase {
public:
    Model();
    ~Model() override = default;
    void clear();

public:
    void set_ability(const std::string&);
    std::string ability() const;
    bool has_ability() const;
    void clear_ability();
private:
    std::string _ability;
    static constexpr int OFFSET_ABILITY = 1;
    static constexpr int QTAG_ABILITY = 1;
    static constexpr int TTAG_ABILITY = 0;

public:
    void set_version(const std::string&);
    std::string version() const;
    bool has_version() const;
    void clear_version();
private:
    std::string _version;
    static constexpr int OFFSET_VERSION = 2;
    static constexpr int QTAG_VERSION = 1;
    static constexpr int TTAG_VERSION = 0;

public:
    void set_infer_type(const std::string&);
    std::string infer_type() const;
    bool has_infer_type() const;
    void clear_infer_type();
private:
    std::string _infer_type;
    static constexpr int OFFSET_INFER_TYPE = 3;
    static constexpr int QTAG_INFER_TYPE = 1;
    static constexpr int TTAG_INFER_TYPE = 0;

public:
    void set_enable(const bool&);
    bool enable() const;
    bool has_enable() const;
    void clear_enable();
private:
    bool _enable;
    static constexpr int OFFSET_ENABLE = 4;
    static constexpr int QTAG_ENABLE = 0;
    static constexpr int TTAG_ENABLE = 0;

public:
    void set_dtype(const std::string&);
    std::string dtype() const;
    bool has_dtype() const;
    void clear_dtype();
private:
    std::string _dtype;
    static constexpr int OFFSET_DTYPE = 5;
    static constexpr int QTAG_DTYPE = 0;
    static constexpr int TTAG_DTYPE = 0;

public:
    void set_device(const std::string&);
    std::string device() const;
    bool has_device() const;
    void clear_device();
private:
    std::string _device;
    static constexpr int OFFSET_DEVICE = 6;
    static constexpr int QTAG_DEVICE = 0;
    static constexpr int TTAG_DEVICE = 0;

public:
    void set_enable_omp(const bool&);
    bool enable_omp() const;
    bool has_enable_omp() const;
    void clear_enable_omp();
private:
    bool _enable_omp;
    static constexpr int OFFSET_ENABLE_OMP = 7;
    static constexpr int QTAG_ENABLE_OMP = 0;
    static constexpr int TTAG_ENABLE_OMP = 0;

public:
    void setVersionCode(int versionCode);
    int versionCode() const;
    void clearVersionCode();
private:
    int _version_code = 0;

public:
    void setExtends(std::string extends);
    std::string extends() const;
    void clearExtends();
private:
    std::string _extends;

protected:
    bool internal_serialize(char* data, int size) const override;
    bool internal_deserialize(const char* data, int size) override;
    bool internal_parse_from_descriptor(plainbuffer::DataDescriptorMap& data_map, const std::string& key) override;
    size_t internal_bytes_size() const override;
    plainbuffer::MessageDescriptorMap internal_get_descriptor() const override;
    std::string internal_get_typename() const override;

private:
    static const plainbuffer::MessageDescriptor _field_tables;
};

class ModelConfig : public plainbuffer::MessageBase {
public:
    ModelConfig();
    ~ModelConfig() override = default;
    void clear();

public:
    void set_product(const std::string&);
    std::string product() const;
    bool has_product() const;
    void clear_product();
private:
    std::string _product;
    static constexpr int OFFSET_PRODUCT = 1;
    static constexpr int QTAG_PRODUCT = 0;
    static constexpr int TTAG_PRODUCT = 0;

public:
    Model* add_model();
    void add_model(const Model&);
    Model model(int) const;
    const std::vector<Model>& model() const;
    bool has_model() const;
    size_t model_size() const;
    void clear_model();
private:
    std::vector<Model> _model;
    static constexpr int OFFSET_MODEL = 3;
    static constexpr int QTAG_MODEL = 2;
    static constexpr int TTAG_MODEL = 1;

protected:
    bool internal_serialize(char* data, int size) const override;
    bool internal_deserialize(const char* data, int size) override;
    bool internal_parse_from_descriptor(plainbuffer::DataDescriptorMap& data_map, const std::string& key) override;
    size_t internal_bytes_size() const override;
    plainbuffer::MessageDescriptorMap internal_get_descriptor() const override;
    std::string internal_get_typename() const override;

private:
    static const plainbuffer::MessageDescriptor _field_tables;
};

} // namespace vision

#endif // PLAIN_BUFFER_GENERATED_MODEL_CONFIG_H
