#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=$(git hash-object -t tree /dev/null)
fi

# 获取pre-commit 的当前目录的父目录
SCRIPT_DIR=$(dirname "$0")

echo "pre-commit dir:$SCRIPT_DIR"

SCRIPT_ABS_PATH=`cd "$SCRIPT_DIR"; pwd`

# 进入这个目录
echo "enter pre-commit dir:$SCRIPT_DIR"

# 执行脚本 gradlew -P checkCommit="true" checkstyle --stacktrace
${SCRIPT_ABS_PATH}/../../gradlew  -P checkCommit="true" checkstyle

# 进入这个目录.-e 是开启转义。执行换行操作
# echo -e "\n check commit result:$?"

if [[ $? -eq 0 ]]
then
   echo  "\n checkstyle OK \n"
else
   echo  "\n checkstyle Error \n"
   exit 1
fi