include ':nyx-github-app'
include ':nyx-github-app-library'

//include ':aura-toolkits'
//project(':aura-toolkits').projectDir = new File('../AuraToolKits/aura-toolkits')

//include ':aura-framework'
//project(':aura-framework').projectDir = new File('../AuraFrameWork/aura-framework')

//include ':aura-ui'
//project(':aura-ui').projectDir = new File('../AuraUI/aura-ui')

