//
// Created by wangyan67 on 2020/9/18.
//

#ifndef VISION_ABILITY_ID_H
#define VISION_ABILITY_ID_H

#include <unordered_map>
#include "vision/VisionAbility.h"

namespace xperf {

inline static std::unordered_map<vision::AbilityId, std::string> ability_id_map {
    { vision::ABILITY_FACE_RECT, "ABILITY_FACE_RECT" },
    { vision::ABILITY_FACE_LANDMARK, "ABILITY_FACE_LANDMARK" },
    { vision::ABILITY_FACE_2DTO3D, "ABILITY_FACE_2DTO3D" },
    { vision::ABILITY_FACE_DANGEROUS_DRIVING, "ABILITY_FACE_DANGEROUS_DRIVING" },
    { vision::ABILITY_FACE_FATIGUE, "ABILITY_FACE_FATIGUE" },
    { vision::ABILITY_FACE_ATTENTION, "ABILITY_FACE_ATTENTION" },
    { vision::ABILITY_FACE_HEAD_BEHAVIOR, "ABILITY_FACE_HEAD_BEHAVIOR" },
    { vision::ABILITY_FACE_EYE_TRACKING, "ABILITY_FACE_EYE_TRACKING" },
    { vision::ABILITY_FACE_EYE_CENTER, "ABILITY_FACE_EYE_CENTER" },
    { vision::ABILITY_FACE_EYE_GAZE, "ABILITY_FACE_EYE_GAZE" },
    { vision::ABILITY_FACE_EYE_WAKING, "ABILITY_FACE_EYE_WAKING" },
    { vision::ABILITY_FACE_INTERACTIVE_LIVING, "ABILITY_FACE_INTERACTIVE_LIVING" },
    { vision::ABILITY_FACE_FEATURE, "ABILITY_FACE_FEATURE" },
    { vision::ABILITY_FACE_CALL, "ABILITY_FACE_CALL" },
    { vision::ABILITY_FACE_AR_HUD, "ABILITY_FACE_AR_HUD" },
    { vision::ABILITY_FACE_NO_INTERACTIVE_LIVING, "ABILITY_FACE_NO_INTERACTIVE_LIVING" },
    { vision::ABILITY_FACE_ATTRIBUTE, "ABILITY_FACE_ATTRIBUTE" },
    { vision::ABILITY_FACE_SMILE, "ABILITY_FACE_SMILE" },
    { vision::ABILITY_FACE_EMOTION, "ABILITY_FACE_EMOTION" },
    { vision::ABILITY_FACE_QUALITY, "ABILITY_FACE_QUALITY" },
    { vision::ABILITY_FACE_IMAGE_COVER, "ABILITY_FACE_IMAGE_COVER" },
    { vision::ABILITY_GESTURE_RECT, "ABILITY_GESTURE_RECT" },
    { vision::ABILITY_GESTURE_LANDMARK, "ABILITY_GESTURE_LANDMARK" },
    { vision::ABILITY_GESTURE_TYPE, "ABILITY_GESTURE_TYPE" },
    { vision::ABILITY_GESTURE_DYNAMIC, "ABILITY_GESTURE_DYNAMIC" },
    { vision::ABILITY_FRAME_BRIGHTNESS, "ABILITY_FRAME_BRIGHTNESS" },
    { vision::ABILITY_HUMAN_POSE, "ABILITY_HUMAN_POSE" },
    { vision::ABILITY_PERSON_VEHICLE_RECT, "ABILITY_PERSON_VEHICLE_RECT" }
};

#define GET_TAG(id) (ability_id_map[id])

}// namespace xperf

#endif //VISION_ABILITY_ID_H
