# -*- coding: utf-8 -*-
"""AIMET installation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14OqZBs_KZp19PvDoOQ8yjV1p3lwI4kWI

**References**

https://github.com/quic/aimet/blob/develop/packaging/google_colab/google_colab_install.md

https://github.com/quic/aimet/blob/develop/packaging/google_colab/Install_AIMET_GoogleColab_torch_cpu.ipynb
"""

import os
import subprocess
import sys
import urllib.request


SOURCE_URL = "https://raw.githubusercontent.com/quic/aimet/develop/packaging/google_colab/"
RELEASE_TAG = "1.18.0.py37"


def install_aimet() -> None:
    """Install the legacy Python 3.7 CPU build used by this Colab example."""
    with urllib.request.urlopen(SOURCE_URL + "reqs_deb_common.txt") as response:
        packages = [
            package
            for line in response.read().decode("utf-8").splitlines()
            for package in line.split()
            if package and not package.startswith("#")
        ]
    subprocess.run(["apt-get", "--assume-yes", "install", *packages], check=True)
    subprocess.run([
        sys.executable,
        "-m",
        "pip",
        "install",
        "-r",
        SOURCE_URL + "reqs_pip_torch_cpu.txt",
        "-f",
        "https://download.pytorch.org/whl/torch_stable.html",
    ], check=True)

    release_url = f"https://github.com/quic/aimet/releases/download/{RELEASE_TAG}"
    for component in ("AimetCommon", "AimetTorch"):
        wheel = f"{component}-torch_cpu_{RELEASE_TAG}-cp37-cp37m-linux_x86_64.whl"
        subprocess.run([sys.executable, "-m", "pip", "install", f"{release_url}/{wheel}"], check=True)


def main() -> None:
    install_aimet()
    sys.path.extend([
        "/usr/local/lib/python3.7/dist-packages/aimet_common/x86_64-linux-gnu",
        "/usr/local/lib/python3.7/dist-packages/aimet_common/x86_64-linux-gnu/"
        "aimet_tensor_quantizer-0.0.0-py3.7-linux-x86_64.egg/",
    ])
    os.environ["LD_LIBRARY_PATH"] = (
        os.environ.get("LD_LIBRARY_PATH", "")
        + ":/usr/local/lib/python3.7/dist-packages/aimet_common/x86_64-linux-gnu"
    )

    import torch
    from torchvision import models
    from aimet_torch.quantsim import QuantizationSimModel

    model = models.resnet18()
    simulation = QuantizationSimModel(model, dummy_input=torch.rand(1, 3, 224, 224))
    print(simulation)


if __name__ == "__main__":
    main()
