[AnswerMocker]
; 控制是否使用模拟答题器
mocker = true
; 答题器数量
answer_num = 20

[ChoiceQue0]
; 0 对整体随机后选择百分比，1 整体顺序百分比
type = 0
; 是否响应 true 响应 false 不响应
action = true
; 选择A的百分比为 25 %，总体加起来为100%
A = 0
B = 100
C = 0
D = 0

[ChoiceQue1]
; 0 对整体随机后选择百分比，1 整体顺序百分比
type = 0
action = true
; 选择A的百分比为 25 %，总体加起来为100%
A = 100
B = 0
C = 0
D = 0

[ChoiceQue2]
; 0 对整体随机后选择百分比，1 整体顺序百分比
type = 0
action = true
; 选择A的百分比为 25 %，总体加起来为100%
A = 0
B = 0
C = 0
D = 0


[RedPacket0]
type = 0
action = true
; 抢红包的人数为50%
choice = 50

[RedPacket1]
type = 0
action = true
; 抢红包的人数为50%
choice = 100

[ChoiceTF0]
type = 0
action = true
; 选择正确的人数为50%
choice_true = 0

[ChoiceTF1]
type = 0
action = true
; 选择正确的人数为50%
choice_true = 100

[Evaluation0]
type = 0
action = true
; 配置分数等级
low_score = 30
mid_score = 70

; 低分(0~30)，中等分数(30~70)，高分的百分比(70~80)
low_score_percent = 100
mid_score_percent = 0
high_score_percent = 0

; 对于句子中单词的得分配置
; 分别设置分数段，设置低分，中等分数的单词数量，其余为高分（若单词数据不够，优先满足高分的数量）
word_low_score = 30
word_mid_score = 70
word_low_score_count = 1
word_mid_score_count = 1


[Evaluation1]
type = 0
action = true
; 配置分数等级
low_score = 30
mid_score = 70

; 低分(0~30)，中等分数(30~70)，高分的百分比(70~80)
low_score_percent = 0
mid_score_percent = 0
high_score_percent = 100

; 对于句子中单词的得分配置
; 分别设置分数段，设置低分，中等分数的单词数量，其余为高分（若单词数据不够，优先满足高分的数量）
word_low_score = 30
word_mid_score = 70
word_low_score_count = 1
word_mid_score_count = 1