set(CONFIG_TAG CmakeConfig)
message(STATUS "[${CONFIG_TAG}] ==================${CONFIG_TAG} Build==============================")

include(utils)

if (NOT DEFINED HOST_OS)
    if (APPLE)
        set(HOST_OS "mac")
    elseif (WIN32)
        set(HOST_OS "windows")
    elseif (UNIX)
        set(HOST_OS "linux")
    else ()
        message(ERROR "Other Host Platform: ${CMAKE_SYSTEM_NAME}")
    endif ()
endif ()
if (NOT DEFINED HOST_ARCH)
    if (CMAKE_HOST_SYSTEM_PROCESSOR MATCHES "x86_64")
        set(HOST_ARCH "x86_64")
    elseif (CMAKE_HOST_SYSTEM_PROCESSOR MATCHES "i386")
        set(HOST_ARCH "i386")
    elseif (CMAKE_HOST_SYSTEM_PROCESSOR MATCHES "i686")
        set(HOST_ARCH "i686")
    elseif (CMAKE_HOST_SYSTEM_PROCESSOR MATCHES "arm64")
        set(HOST_ARCH "arm64")
    else ()
        message(ERROR "Other Host Architecture: ${CMAKE_HOST_SYSTEM_PROCESSOR} !!!!!")
    endif ()
endif ()
# 设置编译目标产物的系统环境版本
# TARGET_OS with values like "windows, osx, linux, android, ios,qnx"
# set(ICP_TARGET_OS qnx)
# set(ICP_TARGET_ARCH aarch64le)
if (NOT DEFINED TARGET_OS)
    set(TARGET_OS ${HOST_OS})    # 如果cmake编译配置没有配置TARGET_OS。则默认设置为HOST_OS
else ()
    set(TARGET_OS ${TARGET_OS})
endif ()
# TARGET_ARCH can be defined as "-DTARGET_ARCH=x86_64"
# TARGET_ARCH with values like "x86, x86_64, armeabi-v7a, arm64-v8a"
# if ANDROID_ABI is defined, the TARGET_ARCH will be automated set
if (NOT DEFINED TARGET_ARCH)
    set(TARGET_ARCH ${HOST_ARCH})
else ()
    set(TARGET_ARCH ${TARGET_ARCH})
endif ()

if (${CMAKE_BUILD_TYPE} MATCHES "Debug")
    set(CMAKE_BUILD_TYPE debug)
    add_definitions(-DDEBUG)
    set(DEBUG True)
elseif (CMAKE_BUILD_TYPE MATCHES "Release")
    set(CMAKE_BUILD_TYPE release)
endif ()
# 设置所要编译的目标平台的标记开关
if (${TARGET_OS} MATCHES linux)
    add_definitions(-DLINUX)
    set(LINUX True)
    set(AURA_BUILD_LINUX True)
    message(STATUS "[${CONFIG_TAG}] [environment] AURA_BUILD_LINUX=${AURA_BUILD_LINUX}")
elseif (${TARGET_OS} MATCHES windows)
    add_definitions(-DWINDOWS)
    set(WINDOWS True)
    set(AURA_BUILD_WINDOWS True)
    message(STATUS "[${CONFIG_TAG}] [environment] AURA_BUILD_WINDOWS=${AURA_BUILD_WINDOWS}")
elseif (${TARGET_OS} MATCHES android)
    add_definitions(-DANDROID)
    set(ANDROID True)
    set(AURA_BUILD_ANDROID True)
    message(STATUS "[${CONFIG_TAG}] [environment] AURA_BUILD_ANDROID=${AURA_BUILD_ANDROID}")
elseif (${TARGET_OS} MATCHES mac)
    add_definitions(-DMAC)
    # 由于现在arm64版本的mac电脑，暂时还没有适配，我们暂时先使用x86_64
    # set(TARGET_ARCH x86_64)
    set(MAC True)
    set(AURA_BUILD_MAC True)
    message(STATUS "[${CONFIG_TAG}] [environment] AURA_BUILD_MAC=${AURA_BUILD_MAC}")
elseif (${TARGET_OS} MATCHES ios)
    add_definitions(-DIOS)
    set(IOS True)
    set(AURA_BUILD_IOS True)
    message(STATUS "[${CONFIG_TAG}] [environment] AURA_BUILD_IOS=${AURA_BUILD_IOS}")
elseif (${TARGET_OS} MATCHES qnx)
    add_definitions(-DQNX)
    add_definitions(-D_QNX_SOURCE)
    set(AURA_BUILD_QNX True)
    message(STATUS "[${CONFIG_TAG}] [environment] AURA_BUILD_QNX=${AURA_BUILD_QNX}")
    if ("${QNX_HOST}" MATCHES ".*710.*")
        set(QNX_VERSION "710")
    elseif ("${QNX_HOST}" MATCHES ".*700.*")
        set(QNX_VERSION "700")
    else ()
        set(QNX_VERSION "Unknown")
    endif ()
    message(STATUS "[${CONFIG_TAG}][Environment] system QNX_VERSION: ${QNX_VERSION}")
    set(QNX True)
endif ()

string(TIMESTAMP AURA_BUILD_TIMESTAMP "%Y-%m-%d %H:%M:%S")

set(AURA_BUILD_GIT_HASH "unknown")
get_git_hash(AURA_BUILD_GIT_HASH)

set(AURA_BUILD_GIT_BRANCH "unknown")
get_git_branch(AURA_BUILD_GIT_BRANCH)

set(AURA_BUILD_HOST_NAME "unknown")
set(AURA_BUILD_HOST_OS   "unknown")
cmake_host_system_information(RESULT AURA_BUILD_HOST_NAME QUERY HOSTNAME)
cmake_host_system_information(RESULT AURA_BUILD_HOST_OS   QUERY OS_VERSION)
set(AURA_BUILD_HOST_INFO "(${AURA_BUILD_HOST_NAME}@${AURA_BUILD_HOST_OS})")

set(AURA_VERSION_DETAILS_TARGET_LEN 1024)
set(AURA_VERSION_DETAILS "${AURA_BUILD_INFO} "
    "${ARUA_BUILD_GIT_BRANCH}:${ARUA_BUILD_GIT_HASH} "
    "${AURA_BUILD_TIMESTAMP} "
    "${AURA_BUILD_HOST_INFO}")
string(LENGTH "${AURA_VERSION_DETAILS}" AURA_VERSION_DETAILS_ORIGINAL_LEN)
math(EXPR PADDING_LEN "${AURA_VERSION_DETAILS_TARGET_LEN} - ${AURA_VERSION_DETAILS_ORIGINAL_LEN}")
add_padding(PADDING ${PADDING_LEN} " ")

message(STATUS "[${CONFIG_TAG}] [environment] AURA_BUILD_TIMESTAMP=${AURA_BUILD_TIMESTAMP}")
message(STATUS "[${CONFIG_TAG}] [environment] AURA_BUILD_GIT_HASH=${AURA_BUILD_GIT_HASH}")
message(STATUS "[${CONFIG_TAG}] [environment] AURA_BUILD_GIT_BRANCH=${AURA_BUILD_GIT_BRANCH}")
message(STATUS "[${CONFIG_TAG}] [environment] AURA_BUILD_HOST_INFO=${AURA_BUILD_HOST_INFO}")
message(STATUS "[${CONFIG_TAG}] [environment] HOST_OS=${HOST_OS}")
message(STATUS "[${CONFIG_TAG}] [environment] HOST_ARCH=${HOST_ARCH}")
message(STATUS "[${CONFIG_TAG}] [environment] TARGET_OS=${TARGET_OS}")
message(STATUS "[${CONFIG_TAG}] [environment] TARGET_ARCH=${TARGET_ARCH}")
# message(STATUS "[${CONFIG_TAG}] [environment] TARGET_BUILD_TYPE=${TARGET_BUILD_TYPE}")
message(STATUS "[${CONFIG_TAG}] [environment] CMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}")
message(STATUS "[${CONFIG_TAG}] [environment] TOOLCHAIN=${CMAKE_TOOLCHAIN_FILE}")

message(STATUS "[${CONFIG_TAG}] ==================${CONFIG_TAG} Build End==============================")