#ifndef VISION_CONSTANTS_H
#define VISION_CONSTANTS_H

namespace aura::vision {

const float ANGEL_180 = 180.f;
/**
 * 弧度转角度转换系数
 */
const float RADIAN_2_ANGLE_FACTOR = 180.f / 3.1415926f;

struct EnumClassHash {
    template<typename T>
    int operator()(T t) const {
        return static_cast<int>(t);
    }
};

enum class Error {
    INIT_FAILURE_FASTCV = -4, // init fastcv failed
    INIT_TIMEOUT = -3,        // init timeout (as QnnPredictor Blocked)
    INIT_FAILURE = -2,
    UNKNOWN_FAILURE = -1,
    OK = 0,

    MODEL_UN_INITED = 1, // model has not been initialized
    MODEL_INIT_ERR = 2,
    PREDICTOR_NULL_ERR = 3,
    INFER_ERR = 4,
    PREPARE_ERR = 5,
    POST_ERR = 6,
    NO_FACE = 7,
    FACE_LMK_ERR = 8,
    NO_GESTURE = 9,
    GESTURE_LMK_ERR = 10,
    NO_CATEGORY = 11,
    NO_HEAD_SHOULDER = 12,

    EYE_DETECTED_UNAVAILABLE = 13,
    INVALID_PARAM = 14,
    MANAGER_ERR = 15,
    BODYLANDMARK_ERR = 16,
    ERR_DISABLED = 17,
    ERR_REQUEST_VERIFY = 18,
    NO_PREDICTOR = 19,
    // 增加初始参数配置校验错误
    INIT_CONFIG_ERR = 20,
    INIT_INITIALIZING_ERR = 21,
    ERROR_PREDICT = 22, // 模型推理器的推理异常，目前用于上报QNN的推理器异常错误
};

enum AbilityId : int {
    ABILITY_UNKNOWN = -1,
    ABILITY_ALL = 1,
    // 人脸相关的检测能力
    ABILITY_FACE = 1000,
    ABILITY_FACE_DETECTION = ABILITY_FACE + 1,
    ABILITY_FACE_RECT = ABILITY_FACE + 10,
    ABILITY_FACE_LANDMARK = ABILITY_FACE + 20,
    ABILITY_FACE_3D_LANDMARK = ABILITY_FACE + 21,
    ABILITY_FACE_LANDMARK_68P = ABILITY_FACE + 22,
    ABILITY_FACE_2DTO3D = ABILITY_FACE + 30,
    ABILITY_FACE_DANGEROUS_DRIVING = ABILITY_FACE + 40,
    ABILITY_FACE_FATIGUE = ABILITY_FACE + 50,
    ABILITY_FACE_ATTENTION = ABILITY_FACE + 60,
    ABILITY_FACE_HEAD_BEHAVIOR = ABILITY_FACE + 70,
    ABILITY_FACE_EYE_TRACKING = ABILITY_FACE + 80,
    ABILITY_FACE_EYE_WAKING = ABILITY_FACE + 81,
    ABILITY_FACE_EYE_CENTER = ABILITY_FACE + 82,
    ABILITY_FACE_EYE_GAZE = ABILITY_FACE + 83,              // EyeGaze 检测能力暂时废弃。使用 3DEyeGaze进行替代
    ABILITY_FACE_3D_EYE_GAZE = ABILITY_FACE + 84,
    ABILITY_FACE_MOUTH_LANDMARK = ABILITY_FACE + 85,
    ABILITY_FACE_INTERACTIVE_LIVING = ABILITY_FACE + 90,
    ABILITY_FACE_FEATURE = ABILITY_FACE + 100,
    ABILITY_FACE_CALL = ABILITY_FACE + 110,
    ABILITY_FACE_AR_HUD = ABILITY_FACE + 120,
    ABILITY_FACE_NO_INTERACTIVE_LIVING = ABILITY_FACE + 130,
    ABILITY_FACE_ATTRIBUTE = ABILITY_FACE + 140,
    ABILITY_FACE_SMILE = ABILITY_FACE + 150,
    ABILITY_FACE_EMOTION = ABILITY_FACE + 160,
    ABILITY_FACE_QUALITY = ABILITY_FACE + 170,
    ABILITY_CAMERA_COVER = ABILITY_FACE + 180,
    ABILITY_FACE_LIP_MOVEMENT = ABILITY_FACE + 190,
    ABILITY_IMAGE_BRIGHTNESS = ABILITY_FACE + 200,
    // 手势相关检测能力
    ABILITY_GESTURE = 2000,
    ABILITY_GESTURE_RECT = ABILITY_GESTURE + 10,
    ABILITY_GESTURE_LANDMARK = ABILITY_GESTURE + 20,
    ABILITY_GESTURE_TYPE = ABILITY_GESTURE + 30,
    ABILITY_GESTURE_DYNAMIC = ABILITY_GESTURE + 40,
    ABILITY_PLAY_PHONE_DETECT = ABILITY_GESTURE + 50,
    // 猫狗宠物婴儿活体相关检测能力
    ABILITY_LIVING = 3000,
    ABILITY_LIVING_DETECTION = ABILITY_LIVING + 10,
    // 身体相关的检测能力
    ABILITY_BODY = 4000,
    ABILITY_BODY_HEAD_SHOULDER = ABILITY_BODY + 10,
    ABILITY_BODY_LANDMARK = ABILITY_BODY + 20,

    ABILITY_PERSON_VEHICLE = 5000,
    ABILITY_PERSON_VEHICLE_RECT = ABILITY_PERSON_VEHICLE + 10,

    ABILITY_FACE_RECONSTRUCT = 6000,

    ABILITY_FRAME = 10000,
    ABILITY_FRAME_BRIGHTNESS = ABILITY_FRAME + 10,
};

enum ModelId : short {
    VISION_TYPE_UNKNOWN = -1,
    VISION_TYPE_FACE_RECT = 100,
    VISION_TYPE_FACE_LANDMARK = VISION_TYPE_FACE_RECT + 10,
    VISION_TYPE_FACE_FEATURE = VISION_TYPE_FACE_RECT + 20,
    VISION_TYPE_FACE_NO_INTERACT_LIVING_RGB = VISION_TYPE_FACE_RECT + 21,
    VISION_TYPE_FACE_NO_INTERACT_LIVING_IR = VISION_TYPE_FACE_RECT + 30,
    VISION_TYPE_FACE_2DTO3D = VISION_TYPE_FACE_RECT + 40,
    VISION_TYPE_FACE_ATTRIBUTE_RGB = VISION_TYPE_FACE_RECT + 50,
    VISION_TYPE_FACE_ATTRIBUTE_IR = VISION_TYPE_FACE_RECT + 51,
    VISION_TYPE_FACE_CALL = VISION_TYPE_FACE_RECT + 60,
    VISION_TYPE_FACE_DANGEROUS_DRIVING = VISION_TYPE_FACE_RECT + 70,
    VISION_TYPE_FACE_DRINK = VISION_TYPE_FACE_RECT + 71,
    VISION_TYPE_GESTURE_RECT = VISION_TYPE_FACE_RECT + 80,
    VISION_TYPE_GESTURE_LANDMARK = VISION_TYPE_FACE_RECT + 81,
    VISION_TYPE_FACE_EMOTION = VISION_TYPE_FACE_RECT + 90,
    VISION_TYPE_FACE_EYE_CENTER = VISION_TYPE_FACE_RECT + 100,
    VISION_TYPE_FACE_EYE_GAZE = VISION_TYPE_FACE_RECT + 101,
    VISION_TYPE_PERSON_BODY = VISION_TYPE_FACE_RECT + 110,
    VISION_TYPE_PERSON_LANDMARK = VISION_TYPE_FACE_RECT + 120,
    VISION_TYPE_FACE_QUALITY = VISION_TYPE_FACE_RECT + 130,
    VISION_TYPE_BIOLOGY_CATEGORY = VISION_TYPE_FACE_RECT + 140,
    VISION_TYPE_HEAD_SHOULDER = VISION_TYPE_FACE_RECT + 150,
    VISION_TYPE_BODY_LANDMARK = VISION_TYPE_FACE_RECT + 160,
    VISION_TYPE_SOURCE1_CAMERA_COVER = VISION_TYPE_FACE_RECT + 170,
    VISION_TYPE_FACE_MOUTH_LANDMARK = VISION_TYPE_FACE_RECT +180,
    VISION_TYPE_FACE_RECONSTRUCT = VISION_TYPE_FACE_RECT + 200
};

enum AbilityCmd : int {
    CMD_RESET_GAZE_CALIB = 1, // 重置视线标定逻辑
};

enum InferenceCmd : int {
    CMD_INFERENCE_POWER_DEFAULT = 1,    // 设置默认能耗级别：默认，对齐QNN实现，其他推理器酌情适配
    CMD_INFERENCE_POWER_BUST = 2,       // 设置默认能耗级别：性能模式，对齐QNN实现，其他推理器酌情适配
    CMD_INFERENCE_POWER_POWER_SAVE = 3, // 设置默认能耗级别：节能模式，对齐QNN实现，其他推理器酌情适配
};

enum CameraLightType : short {
    CAMERA_LIGHT_TYPE_IR = 0,
    CAMERA_LIGHT_TYPE_RGB = 1,
};

enum CameraLightSwapMode : short {
    /** 自动 */
    CAMERA_SWAP_MODE_AUTO = 0,
    /** 手动 */
    CAMERA_SWAP_MODE_MANUAL
};

/**
 * 摄像头source资源列表，与服务层source一一对应
 */
enum Source : int {
    SOURCE_UNKNOWN = 0,
    SOURCE_1 = 1,
    SOURCE_2 = 2,
    SOURCE_3 = 3,
    /** 摄像头Source 的数量3 */
    SOURCE_COUNT = 3
};

enum ReleaseMode : short {
    PRODUCT = 0,
    BENCHMARK_TEST = 1,
    DEMO = 2
};

enum ThreadPolicy: short {
    TP_NORMAL = 0,
    TP_BIG_CORE = 1
};

enum SchedulerMethod : short {
    NAIVE = 1,
    DAG = 2
};

enum SchedulerHtp : short {
    HTP0 = 0,
    HTP1 = 1
};
/**
 * 人脸检测的方法
 */
enum FaceDetectMethod : short {
    DETECT = 0,             // 模型检测（使用算法模型进行检测，目前只支持每帧进行人脸检测）
    TRACK = 1,              // 人脸跟随
    MATCH_TEMPLATE = 2,     // 模板匹配
};

enum ProductNumber {
    MAINLINE = 0,
    JIDU_QNN,
    JIDU_MOBILE,
};

/**
 * @brief 人脸关键点检测的场景，用于配置不同场景下的置信度
 */
enum LandmarkScenario {
    LMK_SCENARIO_NORMAL = 0,
    LMK_SCENARIO_FACEID = 1
};

// Keep sync with opencv->imgproc.hpp
enum FrameConvertFormat : short {
    COPY_BUFFER       = -1,
    COLOR_BGR2RGB     = 4,
    COLOR_BGR2GRAY    = 6,
    COLOR_RGB2GRAY    = 7,
    COLOR_GRAY2RGB    = 8,
    COLOR_GRAY2BGR    = COLOR_GRAY2RGB,

    // YUV 4:2:0 formats family
    COLOR_YUV2RGB_NV12 = 90,
    COLOR_YUV2BGR_NV12 = 91,
    COLOR_YUV2RGB_NV21 = 92,
    COLOR_YUV2BGR_NV21 = 93,
    COLOR_YUV2GRAY_420 = 106,
    COLOR_YUV2GRAY_NV21 = COLOR_YUV2GRAY_420,
    COLOR_YUV2Y_NV21 = 900, // 自定义字段

    //YUV 4:2:2 formats family
    COLOR_YUV2RGB_UYVY = 107,
    COLOR_YUV2BGR_UYVY = 108,
    COLOR_YUV2GRAY_UYVY = 123,
    COLOR_YUV2Y_UYVY = 1000, // 自定义字段
	COLOR_YUV2RGB2BGR = 1001,
	COLOR_RGB2BGR = 1002
};

enum class FrameFormat : short {
    UNKNOWN = 0,
    /** QcAis输出的数据格式，YUV */
    YUV_422_UYVY,
    YUV_420_NV21,
    YUV_420_NV12,
    /** cv::Mat输出的数据格式，BGR */
    BGR,
    RGB,
    /** 输入文件的格式是UYVY的原始Buffer */
    UYVY_BUFFER,
};

enum InteractLivingAction : short {
    INTERACT_LIVING_ACTION_NONE = 0,
    INTERACT_LIVING_ACTION_HEAD_LEFT = 1,
    INTERACT_LIVING_ACTION_HEAD_RIGHT = 2,
    INTERACT_LIVING_ACTION_SHAKE_HEAD = 3,
    INTERACT_LIVING_ACTION_CLOSE_EYES = 4,
    INTERACT_LIVING_ACTION_OPEN_MOUTH = 5
};

/**
 * @brief Length of face points structures
 */
enum PointsLength {
    // the landmark length111w  rghtLM_2D_68_COUNT = 68,
    LM_3D_68_COUNT = 68,
    LM_2D_106_COUNT = 106,
    LM_3D_106_COUNT = 106,
    LM_VIS_2D_72_COUNT = 72,

    // 眼睛眼睑关键点数量
    LM_EYE_2D_8_COUNT = 8,
    LM_EYE_3D_8_COUNT = 8,
    // Mouth关键点数量
    LM_MOUTH_2D_20_COUNT = 20,
    // 眼睛关键点数量
    LM_EYE_2D_28_COUNT = 28,
    LM_EYE_3D_28_COUNT = 28,
    // the face feature vector length
    FEATURE_COUNT = 1024,
    // 手势关键点数量
    GESTURE_LM_21_COUNT = 21,
    // body landmark num
    BODY_LM_2D_12_COUNT = 12
};

/**
 * @brief 2d landmark (68 points) definition
 * note:一般示意图的关键点是从1开始绘制，代码定义从0开始定义
 */
enum FaceLandmark68 : short {
    // face contour: 0~16
    FLM68_0_CT_LEFT1 = 0,             // 关键点轮廓左侧点
    FLM68_1_CT_LEFT2 = 1,
    FLM68_2_CT_LEFT3 = 2,
    FLM68_3_CT_LEFT4 = 3,
    FLM68_4_CT_LEFT5 = 4,
    FLM68_5_CT_LEFT6 = 5,
    FLM68_6_CT_LEFT7 = 6,
    FLM68_7_CT_LEFT8 = 7,
    FLM68_8_CT_CHIN9 = 8,             //下巴
    FLM68_9_CT_RIGHT10 = 9,           // 关键点轮廓右侧点
    FLM68_10_CT_RIGHT11 = 10,
    FLM68_11_CT_RIGHT12 = 11,
    FLM68_12_CT_RIGHT13 = 12,
    FLM68_13_CT_RIGHT14 = 13,
    FLM68_14_CT_RIGHT15 = 14,
    FLM68_15_CT_RIGHT16 = 15,
    FLM68_16_CT_RIGHT17 = 16,
    // left eyebrow：17~21
    FLM68_17_L_EYEBROW_LEFT_CORNER = 17,            // 左眼眉头
    FLM68_18_L_EYEBROW_LEFT_QUARTER = 18,
    FLM68_19_L_EYEBROW_MIDDLE = 19,
    FLM68_20_L_EYEBROW_RIGHT_QUARTER = 20,
    FLM68_21_L_EYEBROW_RIGHT_CORNER = 21,
    // right eyebrow：22～26
    FLM68_22_R_EYEBROW_LEFT_CORNER = 22,            // 右眼眉头
    FLM68_23_R_EYEBROW_LEFT_QUARTER = 23,
    FLM68_24_R_EYEBROW_MIDDLE = 24,
    FLM68_25_R_EYEBROW_RIGHT_QUARTER = 25,
    FLM68_26_R_EYEBROW_RIGHT_CORNER = 26,
    // nose：27～35
    FLM68_27_NOSE_BRIDGE1 = 27,                     // 鼻梁
    FLM68_28_NOSE_BRIDGE2 = 28,
    FLM68_29_NOSE_BRIDGE3 = 29,
    FLM68_30_NOSE_TIP = 30,                         // 鼻尖
    FLM68_31_NOSE_BELOW_LEFT_CORNER = 31,           // 鼻子下方关键点
    FLM68_32_NOSE_BELOW_LEFT_QUARTER = 32,
    FLM68_33_NOSE_BELOW_MIDDLE = 33,
    FLM68_34_NOSE_BELOW_RIGHT_QUARTER = 34,
    FLM68_35_NOSE_BELOW_RIGHT_CORNER = 35,
    // left eye：36～41
    FLM68_36_L_EYE_LEFT_CORNER = 36,
    FLM68_37_L_EYE_TOP_LEFT_QUARTER = 37,
    FLM68_38_L_EYE_TOP_RIGHT_QUARTER = 38,
    FLM68_39_L_EYE_RIGHT_CORNER = 39,
    FLM68_40_L_EYE_LOWER_RIGHT_QUARTER = 40,
    FLM68_41_L_EYE_LOWER_LEFT_QUARTER = 41,
    // right eye：42～47
    FLM68_42_R_EYE_LEFT_CORNER = 42,
    FLM68_43_R_EYE_TOP_LEFT_QUARTER = 43,
    FLM68_44_R_EYE_TOP_RIGHT_QUARTER = 44,
    FLM68_45_R_EYE_RIGHT_CORNER = 45,
    FLM68_46_R_EYE_LOWER_RIGHT_QUARTER = 46,
    FLM68_47_R_EYE_LOWER_LEFT_QUARTER = 47,
    // mouth：86～105
    FLM68_48_MOUTH_LEFT_CORNER = 48,
    FLM68_49_MOUTH_TOP_LIP_LEFT_CT1 = 49,
    FLM68_50_MOUTH_TOP_LIP_TOP = 50,
    FLM68_51_MOUTH_TOP_LIP_RIGHT_CT1 = 51,
    FLM68_52_MOUTH_RIGHT_CORNER = 52,
    FLM68_53_MOUTH_LOWER_LIP_BOTTOM = 53,
    FLM68_54_MOUTH_TOP_LIP_LEFT_CT2 = 54,
    FLM68_55_MOUTH_TOP_LIP_RIGHT_CT2 = 55,
    FLM68_56_MOUTH_LOWER_LIP_RIGHT_CT1 = 56,
    FLM68_57_MOUTH_LOWER_LIP_LEFT_CT1 = 57,
    FLM68_58_MOUTH_LEFT_INNER_CORNER = 58,
    FLM68_59_MOUTH_RIGHT_INNER_CORNER = 59,
    FLM68_60_MOUTH_TOP_LIP_BOTTOM_LEFT = 60,
    FLM68_61_MOUTH_TOP_LIP_BOTTOM_TOP = 61,
    FLM68_62_MOUTH_TOP_LIP_BOTTOM_RIGHT = 62,
    FLM68_63_MOUTH_LOWER_LIP_TOP_LEFT = 63,
    FLM68_64_MOUTH_LOWER_LIP_TOP_BOTTOM = 64,
    FLM68_65_MOUTH_LOWER_LIP_TOP_RIGHT = 65,
    FLM68_66_MOUTH_LOWER_LIP_LEFT_CT2 = 66,
    FLM68_67_MOUTH_LOWER_LIP_RIGHT_CT2 = 67
};



} // namespace vision

#endif //VISION_CONSTANTS_H