# -*- coding: utf-8 -*-
"""AIMET Installation - torch gpu.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Toozq8coZ1jKUDe-xKRKofB9QMSrHCzn

**References**

https://github.com/quic/aimet/blob/develop/packaging/google_colab/Install_AIMET_GoogleColab_torch_gpu.ipynb
"""

import os
import os
import sys
import os

import torch
from torchvision import models
from aimet_torch.quantsim import QuantizationSimModel
m = models.resnet18().cuda()
sim = QuantizationSimModel(m, dummy_input=torch.rand(1, 3, 224, 224).cuda())
print(sim)