include_guard(GLOBAL)

# Shared platform configuration. Explicit -DHOST_*/-DTARGET_* values always
# win; otherwise values are inferred from CMake's host and target systems so
# toolchain-based cross compilation works without duplicating platform logic.

function(_aura_normalize_os input_value output_var)
    string(TOLOWER "${input_value}" normalized)
    if(normalized MATCHES "^(darwin|macos|osx)$")
        set(normalized "mac")
    elseif(normalized MATCHES "^(windows|windowsstore|msys|mingw|cygwin)$")
        set(normalized "windows")
    elseif(normalized STREQUAL "qnx")
        set(normalized "qnx")
    elseif(normalized STREQUAL "ios")
        set(normalized "ios")
    elseif(normalized STREQUAL "android")
        set(normalized "android")
    elseif(normalized STREQUAL "linux")
        set(normalized "linux")
    else()
        # Keep vendor/SoC platform identifiers (for example AX620A) usable by
        # external toolchain files while standard platforms stay normalized.
        message(WARNING "Using custom target operating system: ${input_value}")
    endif()
    set(${output_var} "${normalized}" PARENT_SCOPE)
endfunction()

function(_aura_normalize_arch input_value output_var)
    string(TOLOWER "${input_value}" normalized)
    if(normalized MATCHES "^(amd64|x64|x86_64)$")
        set(normalized "x86_64")
    elseif(normalized MATCHES "^(aarch64|arm64)$")
        set(normalized "arm64")
    elseif(normalized MATCHES "^(x86|i[3-6]86)$")
        set(normalized "x86")
    endif()
    set(${output_var} "${normalized}" PARENT_SCOPE)
endfunction()

if(DEFINED HOST_OS AND NOT HOST_OS STREQUAL "")
    _aura_normalize_os("${HOST_OS}" _aura_host_os)
else()
    _aura_normalize_os("${CMAKE_HOST_SYSTEM_NAME}" _aura_host_os)
endif()

if(DEFINED HOST_ARCH AND NOT HOST_ARCH STREQUAL "")
    _aura_normalize_arch("${HOST_ARCH}" _aura_host_arch)
else()
    _aura_normalize_arch("${CMAKE_HOST_SYSTEM_PROCESSOR}" _aura_host_arch)
endif()

if(DEFINED TARGET_OS AND NOT TARGET_OS STREQUAL "")
    _aura_normalize_os("${TARGET_OS}" _aura_target_os)
else()
    _aura_normalize_os("${CMAKE_SYSTEM_NAME}" _aura_target_os)
endif()

if(DEFINED TARGET_ARCH AND NOT TARGET_ARCH STREQUAL "")
    _aura_normalize_arch("${TARGET_ARCH}" _aura_target_arch)
elseif(ANDROID_ABI)
    set(_aura_target_arch "${ANDROID_ABI}")
else()
    _aura_normalize_arch("${CMAKE_SYSTEM_PROCESSOR}" _aura_target_arch)
endif()

set(HOST_OS "${_aura_host_os}" CACHE STRING "Host operating system" FORCE)
set(HOST_ARCH "${_aura_host_arch}" CACHE STRING "Host architecture" FORCE)
set(TARGET_OS "${_aura_target_os}" CACHE STRING "Target operating system" FORCE)
set(TARGET_ARCH "${_aura_target_arch}" CACHE STRING "Target architecture or ABI" FORCE)
set_property(CACHE TARGET_OS PROPERTY STRINGS mac linux windows android ios qnx)

if(CMAKE_CONFIGURATION_TYPES)
    set(AURA_BUILD_TYPE "$<LOWER_CASE:$<CONFIG>>")
elseif(CMAKE_BUILD_TYPE)
    string(TOLOWER "${CMAKE_BUILD_TYPE}" AURA_BUILD_TYPE)
else()
    set(AURA_BUILD_TYPE "release")
endif()
set(AURA_DEPENDENCY_VARIANT "release" CACHE STRING
    "Prebuilt dependency variant (usually release or debug)")
set_property(CACHE AURA_DEPENDENCY_VARIANT PROPERTY STRINGS release debug)

set(AURA_PLATFORM_ID "${TARGET_OS}-${TARGET_ARCH}")
set(AURA_BUILD_MAC FALSE)
set(AURA_BUILD_LINUX FALSE)
set(AURA_BUILD_WINDOWS FALSE)
set(AURA_BUILD_WIN FALSE)
set(AURA_BUILD_ANDROID FALSE)
set(AURA_BUILD_IOS FALSE)
set(AURA_BUILD_QNX FALSE)

if(TARGET_OS STREQUAL "mac")
    set(AURA_BUILD_MAC TRUE)
    set(MAC TRUE)
    add_compile_definitions(MAC=1 AURA_BUILD_MAC=1)
elseif(TARGET_OS STREQUAL "linux")
    set(AURA_BUILD_LINUX TRUE)
    set(LINUX TRUE)
    add_compile_definitions(LINUX=1 AURA_BUILD_LINUX=1)
elseif(TARGET_OS STREQUAL "windows")
    set(AURA_BUILD_WINDOWS TRUE)
    set(AURA_BUILD_WIN TRUE)
    set(WINDOWS TRUE)
    add_compile_definitions(WINDOWS=1 AURA_BUILD_WINDOWS=1 AURA_BUILD_WIN=1)
elseif(TARGET_OS STREQUAL "android")
    set(AURA_BUILD_ANDROID TRUE)
    set(ANDROID TRUE)
    add_compile_definitions(ANDROID=1 AURA_BUILD_ANDROID=1)
elseif(TARGET_OS STREQUAL "ios")
    set(AURA_BUILD_IOS TRUE)
    set(IOS TRUE)
    add_compile_definitions(IOS=1 AURA_BUILD_IOS=1)
elseif(TARGET_OS STREQUAL "qnx")
    set(AURA_BUILD_QNX TRUE)
    set(QNX TRUE)
    add_compile_definitions(QNX=1 _QNX_SOURCE=1 AURA_BUILD_QNX=1)
endif()

if(AURA_BUILD_QNX)
    if(DEFINED ENV{QNX_HOST} AND "$ENV{QNX_HOST}" MATCHES "710")
        set(QNX_VERSION "710")
    elseif(DEFINED ENV{QNX_HOST} AND "$ENV{QNX_HOST}" MATCHES "700")
        set(QNX_VERSION "700")
    else()
        set(QNX_VERSION "Unknown")
    endif()
endif()

option(AURA_ENABLE_WARNINGS "Enable common compiler warnings" ON)
option(AURA_WARNINGS_AS_ERRORS "Treat compiler warnings as errors" OFF)

function(aura_apply_platform target_name)
    if(NOT TARGET "${target_name}")
        message(FATAL_ERROR "aura_apply_platform: unknown target ${target_name}")
    endif()

    target_compile_definitions("${target_name}" PRIVATE
        AURA_TARGET_OS=\"${TARGET_OS}\"
        AURA_TARGET_ARCH=\"${TARGET_ARCH}\")

    if(MSVC)
        target_compile_options("${target_name}" PRIVATE /utf-8 /permissive-)
        target_compile_definitions("${target_name}" PRIVATE
            NOMINMAX=1 WIN32_LEAN_AND_MEAN=1 _CRT_SECURE_NO_WARNINGS=1)
        if(AURA_ENABLE_WARNINGS)
            target_compile_options("${target_name}" PRIVATE /W4)
        endif()
        if(AURA_WARNINGS_AS_ERRORS)
            target_compile_options("${target_name}" PRIVATE /WX)
        endif()
    elseif(CMAKE_CXX_COMPILER_ID MATCHES "Clang|GNU")
        if(AURA_ENABLE_WARNINGS)
            target_compile_options("${target_name}" PRIVATE -Wall -Wextra -Wpedantic)
        endif()
        if(AURA_WARNINGS_AS_ERRORS)
            target_compile_options("${target_name}" PRIVATE -Werror)
        endif()
    endif()

    if(AURA_BUILD_LINUX AND NOT ANDROID)
        set(THREADS_PREFER_PTHREAD_FLAG ON)
        find_package(Threads REQUIRED)
        target_link_libraries("${target_name}" PRIVATE Threads::Threads)
    endif()
endfunction()

message(STATUS "[AuraPlatform] host=${HOST_OS}-${HOST_ARCH}")
message(STATUS "[AuraPlatform] target=${AURA_PLATFORM_ID}, build=${AURA_BUILD_TYPE}")
if(CMAKE_CROSSCOMPILING)
    if(CMAKE_TOOLCHAIN_FILE)
        message(STATUS "[AuraPlatform] cross-compiling with ${CMAKE_TOOLCHAIN_FILE}")
    else()
        message(STATUS "[AuraPlatform] cross-compiling for ${CMAKE_SYSTEM_NAME}")
    endif()
endif()
